name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.x'

    - name: Install Tools
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: SonarCloud Begin
      working-directory: ./src
      run: dotnet sonarscanner begin /k:"elixneto_CollectionMapper.RavenDB.NetCore" /o:"elixnetogithub" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.cobertura.reportsPaths="coverage-report/Cobertura.xml"

    - name: Build
      working-directory: ./src
      run: dotnet build

    - name: Test with Coverage
      working-directory: ./src
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

    - name: Merge Coverage Reports
      working-directory: ./src
      run: |
        reportgenerator -reports:TestResults/**/coverage.cobertura.xml \
                        -targetdir:coverage-report \
                        -reporttypes:Cobertura

    - name: SonarCloud End
      working-directory: ./src
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"